### ISSUE TITLE
Using for other webs

### ISSUE THREAD

**Issue by DiMiTriFrog** [no-name-user-name/tiktok-puzzle-captcha-solver#1]
I'm trying to use this for other webs but the size of de drag button its different than tiktok's drag button. In this case the size is less.

How could I do the code works for other sizes?

**Comment by no-name-user-name** [comment]
Size matters? Need to test. Attach a link to the desired captcha.

**Comment by DiMiTriFrog** [comment]
Hi!

The captcha shows when you try to register in coinmarektcap.ocm

**Comment by no-name-user-name** [comment]
edit some functions:


```
	def login(self,username,password):
		self.start_chrome()

		self.driver.get('https://coinmarketcap.com/')

		### input form selectors
		self.driver.find_element(By.CLASS_NAME,'naMuB').click() # Sing Up
		# self.driver.find_element(By.CLASS_NAME,'DnSnS').click() # Log In
		self.driver.find_element(By.CSS_SELECTOR,'input[type="email"]').send_keys(username)
		self.driver.find_element(By.CSS_SELECTOR,'input[type="password"]').send_keys(password)
		self.driver.find_element(By.CLASS_NAME,'hSsFuv').click()


		try:
			### captcha image selector
			self.driver.find_element(By.CLASS_NAME,"css-jyuqmw")
			while 1:
				ans = self.solve_captcha()
				if ans['success']:
					break
				sleep(4)
		except Exception as e:
			pass
```


```
	def solve_captcha(self):
		while 1:
			try:    
				### captcha image selector
				img = self.driver.find_element(By.CLASS_NAME,"css-jyuqmw")
				div_style = img.get_attribute('style')

				### check if img load
				if 'background-image' in div_style:
					sleep(1)
					img.screenshot('foo.png')
					break

			except Exception as e:
				print('wait img load...')

		img = cv.imread('foo.png')
		gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
		corners = cv.goodFeaturesToTrack(gray,15,0.05,1)
		corners = np.int0(corners)

		x_Array = []
		for i in corners:
			x,y = i.ravel()
			cv.circle(img,(x,y),3,255,-1)
			if x > 70:
				x_Array.append(x)

		x_Array.sort()
		print(x_Array)      

		source = self.driver.find_element(By.CLASS_NAME,"css-1stu6rw")
		source_location = source.location
		source_size = source.size

		array = [170, 345, 400, 400, 345] 
		unic = Counter(x_Array)
		for x in x_Array:
			if unic[x] > 1:
				x_offset = x-8
				break

		y_offset = 0
		action = ActionChains(self.driver)
		try:
			steps_count = 5
			step = (x_offset)/steps_count
			act_1 = action.click_and_hold(source)
			for x in range(0,steps_count):
				act_1.move_by_offset(step, y_offset)
			act_1.release().perform()

			msg = self.driver.find_element(By.CLASS_NAME,'msg').find_element(By.TAG_NAME,'div').text
			while msg == '':
				msg = self.driver.find_element(By.CLASS_NAME,'msg').find_element(By.TAG_NAME,'div').text
			print(msg)

			if 'Верификация пройдена' in msg or 'complete' in msg:
				return {'success':1}
			else:
				return {'success':0}

		except Exception as e:
			print(e)

```

**Comment by DiMiTriFrog** [comment]
Thank you for the response. I dit it but there is an error -> Too many tries.  Seems that its needed slide one time without steps.

I change for do it in one. step, but the piece its dragged a little left to the needed position. I think the difference its:

pieze width - drag button width


Its working with this way and only with one  step. But I dont know why  cmc shows the error too many attempts
<img width="492" alt="Screen Shot 2022-06-22 at 13 55 38" src="https://user-images.githubusercontent.com/38754548/175023418-580719f5-a11f-436e-a2db-80873d778e55.png">

**Comment by DiMiTriFrog** [comment]
> Thank you for the response. I dit it but there is an error -> Too many tries. Seems that its needed slide one time without steps.
> 
> I change for do it in one. step, but the piece its dragged a little left to the needed position. I think the difference its:
> 
> pieze width - drag button width
> 
> Its working with this way and only with one step. But I dont know why cmc shows the error too many attempts <img alt="Screen Shot 2022-06-22 at 13 55 38" width="492" src="https://user-images.githubusercontent.com/38754548/175023418-580719f5-a11f-436e-a2db-80873d778e55.png">

Any solution for this??

**Comment by no-name-user-name** [comment]
@DiMiTriFrog use proxy

**Comment by DiMiTriFrog** [comment]
With new proxies seems work good!, but I check that have so wrong attempts,  I mean.. the puzzle isnt solving right, there are a X difference between the real piece and the solution.
